# Generated by Django 3.0.2 on 2020-04-12 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='email_1',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='first_name_1',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='last_name_1',
            new_name='last_name',
        ),
    ]
