# Generated by Django 3.0.5 on 2020-04-24 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200423_1046'),
    ]

    database_operations = [
        migrations.AlterModelTable('Company', 'api_company'),
        migrations.AlterModelTable('University', 'api_university')
    ]

    state_operations = [
        migrations.DeleteModel('Company'),
        migrations.DeleteModel('University')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
