# Generated by Django 3.0.5 on 2020-04-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200424_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='university',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
