# Generated by Django 3.0.5 on 2020-04-24 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_auto_20200423_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='thread_id',
            new_name='thread',
        ),
        migrations.RenameField(
            model_name='userthread',
            old_name='thread_id',
            new_name='thread',
        ),
        migrations.RenameField(
            model_name='userthread',
            old_name='user_id',
            new_name='user',
        ),
    ]
